[build.environment]
CI = "true"
NODE_VERSION = "10"
NPM_CONFIG_OPTIONAL = "false"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[build]
command = "node_modules/.bin/antora antora-playbook.yml --stacktrace --log-format=pretty"

[[redirects]]
  from = "https://docs-thoughtspot-com.netlify.app/software/latest/docs/*"
  to = "https://docs-thoughtspot-com.netlify.app/software/latest/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
